name: release
on:
  push:
    branches:
      - master
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: johnnys318/htwr-aachen
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enabled=true
            type=sha
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: "${{ github.event_name != 'pull_request'}}"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels}}"
          file: "docker/production/Dockerfile"
          platforms: linux/amd64,linux/arm64
    # - name: Deployment Hook
    #   uses: distributhor/workflow-webhook@v3
    #   with:
    #     webhook_url: "${{secrets.WEBHOOK_URL}}"
    #     webhook_secret: "${{secrets.WEBHOOK_SECRET}}"
